spring.application.name=byteCore API

# H2 para desenvolvimento
spring.datasource.url=jdbc:h2:mem:bytemarket
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:dGVzdGVkZWNoYXZlc2VjcmV0YXBhcmsyNTZiaXRzcXVlbmFvZmFsaGE=}
jwt.expirationMs=${JWT_EXPIRATION:86400000}

admin_email=${ADMIN_EMAIL:kayk@teste.com}
admin_password=${ADMIN_PASSWORD:123456}

mercadopago.public_key=${MERCADOPAGO_PUBLIC_KEY:TEST-public-key-falsa}
mercadopago.access_token=${MERCADOPAGO_ACCESS_TOKEN:TEST-access-token-falso}
mercadopago.webhook=${MERCADOPAGO_WEBHOOK:http://localhost:8080/webhook}
mercadopago.webhook.secret=${MERCADOPAGO_WEBHOOK_SECRET:segredo_falso}

app.base-url=${APP_BASE_URL:http://localhost:8080}

payment.pix.expiration-minutes=${PAYMENT_PIX_EXPIRATION_MINUTES:30}

logging.level.root=INFO
logging.level.com.byteCore.demo=DEBUG

# TAXA DA PLATAFORMA
bytemarket.fee.percentage=0.05

#CORES
spring.output.ansi.enabled=ALWAYS

app.cors.allowed-origins=http://localhost:5173

# Data (Cinza) | Nivel (Colorido) | PID (Magenta) | Thread | Classe (Ciano) | Mensagem
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

# --- EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER:usuario_teste@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:senha_teste_123}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=5000
spring.mail.properties.mail.writetimeout=5000
bytemarket.email.from=${EMAIL_USER:usuario_teste@gmail.com}
bytemarket.email.name=ByteMarket Store